### ISSUE TITLE
Extraction of CSS files with MiniCssExtractPlugin

### ISSUE THREAD

**Issue by arathael** [SoarLin/pug-sass-template#28]
Hello, I was just playing around with this boilerplate and noted that it does not extract the CSS into an external file using MiniCssExtractPlugin, I tried my best to install v1.6.2 and try to setup but docs are really old and not that verbose. Do you have any alternative or recipe for generating .css files and attaching a link element to head automagically?

I also tried updating webpack to v5 but that required to update most deps and config.

**Comment by SoarLin** [comment]
I think the fastest way is to install the **old** version MiniCssExtractPlugin(e.g. version 0.9.0), it can be installed with the following command

`npm install --save-dev mini-css-extract-plugin@0.9.0`

and modify the webpack.config.js as below

```
// add require MiniCssExtractPlugin
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

// add plugin setting into plugin array
plugins: [
      // ....
      new MiniCssExtractPlugin({
        filename: 'css/style.css',
      }),
      // ...
]

// change style-loader to MiniCssExtractPlugin.loader
module: {
    rules: [
        {
          test: /\.s[ac]ss$/i,
          use: [
            MiniCssExtractPlugin.loader,
            'css-loader',
            {
              loader: 'sass-loader',
              options: {
                sourceMap: true,
              }
            }
          ]
        },
    ]
}
```

then run `npm run build`, you can preprocess sass and get the extract style.css in the `dist/css` folder

I have added an `extract-css` branch for reference
